api_version = "2025-07"

[[extensions]]
name = "t:name"
handle = "tradepro-discount"
type = "function"
uid = "630829f6-2180-df6b-6a08-656aa871d3f31c3e344a"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.lines.discounts.generate.run"
  input_query = "src/cart_lines_discounts_generate_run.graphql"
  export = "cart-lines-discounts-generate-run"


  [extensions.build]
  command = ""
  path = "dist/function.wasm"

[extensions.ui]
handle = "tradepro-discount-ui"