api_version = "2025-04"

[[extensions]]
# Change the merchant-facing name of the extension in locales/en.default.json
name = "t:name"
description = "t:description"
handle = "tradepro-discount-ui"
type = "ui_extension"
uid = "92cba0be-899a-384c-d133-2501e9496cbf387f508e"

# Only 1 target can be specified for each Admin block extension
[[extensions.targeting]]
module = "./src/index.tsx"
# The target used here must match the target used in the module file (./src/index.tsx)
target = "admin.discount-details.function-settings.render"
